[2024-05-18T11:53:44.723+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T11:53:44.749+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_classification.preprocess_data manual__2024-05-18T06:23:35.195255+00:00 [queued]>
[2024-05-18T11:53:44.755+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_classification.preprocess_data manual__2024-05-18T06:23:35.195255+00:00 [queued]>
[2024-05-18T11:53:44.755+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 0
[2024-05-18T11:53:44.764+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-05-18 06:23:35.195255+00:00
[2024-05-18T11:53:44.769+0530] {standard_task_runner.py:63} INFO - Started process 36925 to run task
[2024-05-18T11:53:44.771+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-18T11:53:44.777+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'iris_classification', 'preprocess_data', 'manual__2024-05-18T06:23:35.195255+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/fy/4q0txy357vvc35bhsxlfyr8c0000gn/T/tmpv1d5reg3']
[2024-05-18T11:53:44.780+0530] {standard_task_runner.py:91} INFO - Job 109: Subtask preprocess_data
[2024-05-18T11:53:44.824+0530] {task_command.py:426} INFO - Running <TaskInstance: iris_classification.preprocess_data manual__2024-05-18T06:23:35.195255+00:00 [running]> on host aswins-macbook-air.local
[2024-05-18T11:53:44.883+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='iris_classification' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T06:23:35.195255+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T06:23:35.195255+00:00'
[2024-05-18T11:53:44.884+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T11:56:40.799+0530] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-05-18T11:56:40.804+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-18T11:56:40.811+0530] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 36925. PIDs of all processes in the group: [36925]
[2024-05-18T11:56:40.811+0530] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 36925
[2024-05-18T11:56:40.813+0530] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-18T11:56:40.816+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T11:56:40.872+0530] {process_utils.py:80} INFO - Process psutil.Process(pid=36925, status='terminated', exitcode=0, started='11:53:44') (36925) terminated with exit code 0
